### ISSUE TITLE
Reversed Persian Titles

### ISSUE THREAD

**Issue by mitinull** [mahdimirza/django-rest-app-for-showing-university-foods#3]
The persian titles for meals is reversed for me.
It's like this:
![image](https://github.com/user-attachments/assets/33c6ac3d-cb33-46b8-a1e5-197fecd2ca4f)

I think it should probably be `lunch + day` not `day + lunch`

**Comment by mahdimirza** [comment]
fixed.

**Comment by mahdimirza** [comment]
fixed
